baseURL = "https://www.tomhoule.com/"
languageCode = "en-us"
title = "Tom Houle's homepage"

[permalinks]
blog = "/:slug/"

[params]
description = "Tom Houle's homepage"
homeMetaContent = "Tom Houle's homepage"
footer = "ðŸŒ¹ caute"
dateFormat = "2006-01-02"

[imaging]
quality = 99

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 4

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[markup.tableOfContents]
endLevel = 6
startLevel = 2
